### ISSUE TITLE
Briefcase opening sound

### ISSUE THREAD

**Issue by LeRutY** [ineedbots/bo1_bot_warfare#9] opened 2022-01-30 18:43 UTC
Suggesting making it audible only if the player is planting or defusing the bomb

**Comment by ineedbots** [comment] 2022-03-19 03:38
when using the patch_mp.ff, theres a loadsound missing from it, using the official patch_mp fixes this,

solution is to make a proper patch_mp version

**Comment by ineedbots** [comment] 2022-03-19 03:40
dupe of #7

**Closed as completed by ineedbots** 2022-03-19 03:40 UTC
