### ISSUE TITLE
DLC Maps Loading screen/radar just blocks

### ISSUE THREAD

**Issue by LevelChecker** [ineedbots/bo1_bot_warfare#7] opened 2021-11-28 22:12 UTC
The minimap/radar are shown as just grey blocks as if it cannot be loaded if you use the Patch mp files included, however these files are needed to use on a dedicated server, is there any way to get them to work with the dlc map graphic/minimaps working?

**Comment by ineedbots** [comment] 2022-03-19 03:41
needs a better solution for using patch_mp.ff

**Comment by ineedbots** [comment] 2022-03-19 03:41
dupe of #5

**Closed as completed by ineedbots** 2022-03-19 03:41 UTC
