### ISSUE TITLE
Presteging doesn't reset level back to 1, Stuck with Infinite Money

### ISSUE THREAD

**Issue by RyuAzuku** [ineedbots/bo1_bot_warfare#11] opened 2022-04-15 07:55 UTC
As the title says prestige-ing doesn't reset your level back to 1. It does relock all weapons equipment ETC but you will be at max level. To go along with this for some reason my money does not go down when I buy things. 

EDIT: Turns out my money neither increases nor decreases, shame because there are a few things I can't buy now! This can be fixed by just going back to unmodded, but then I can't play with the upgraded bots.

The only thing I could think that might be causing an issue was the fact I was already max level before installing the mod. 

Hope you get around to updating the mod because it is still quite fun!

**Comment by Gunscrusader** [comment] 2022-06-29 09:18
Hi im experiencing this too!

Just out of interest, this has todo with the mod itself. I played combat training before and after loading this mod in combat training in both vanilla blops and plutonium.

I would appreciate it if this can get fixed. Kinda breaks the progression

**Comment by ineedbots** [comment] 2024-01-20 06:48
Dupe of #2

**Closed as completed by ineedbots** 2024-01-20 06:48 UTC
